/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimulatorViewer.java
 *
 * Created on May 20, 2009, 3:55:22 PM
 */

package plcedit;

import org.jhotdraw.draw.DrawingEditor;
import org.jhotdraw.draw.Figure;

/**
 *
 * @author huangkf
 */
public class Simulator extends javax.swing.JFrame {

    /** Creates new form SimulatorViewer */
    public Simulator(DrawingEditor editor) {
        initComponents();
        this.editor = editor;
    }

    private DrawingEditor editor;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TableScrollablePane = new javax.swing.JScrollPane();
        VariableTable = new javax.swing.JTable();
        btnStepOnce = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnStepNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VariableTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Variable", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableScrollablePane.setViewportView(VariableTable);

        btnStepOnce.setText("Step Once");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnStepNext.setText("Step Next");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(TableScrollablePane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(btnReset)
                .add(18, 18, 18)
                .add(btnStepOnce)
                .add(18, 18, 18)
                .add(btnStepNext)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(TableScrollablePane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 247, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnReset)
                    .add(btnStepOnce)
                    .add(btnStepNext))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    /**
    * @param args the command line arguments
    */
    /* Disabled section because we do not want this class to execute main
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulator(null).setVisible(true);
            }
        });
    }*/


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TableScrollablePane;
    private javax.swing.JTable VariableTable;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStepNext;
    private javax.swing.JButton btnStepOnce;
    // End of variables declaration//GEN-END:variables



    private CodeBlockFigure findStartBlock()
    {
        int FigCount = 0;
        CodeBlockFigure startfig = null;

        for (Figure block : editor.getActiveView().getDrawing().getChildren())
        {
            if (((CodeBlockFigure)block).getType() == CodeType.Start)
            {
                startfig = (CodeBlockFigure)block;
                FigCount++;
            }
        }

        if (FigCount > 1)
        {

        }

        //FIXME: FIND THE ATTRIBUTE TO CHANGE COLOUR
        //startfig.setAttribute( , rootPane);

        return startfig;
    }
}
